### ISSUE TITLE
The cheat is not working!

### ISSUE THREAD

**Issue by theotherone-1** [JokinAce/CSGO-Python-Pymem-Cheat-Hack#6]
Error:
Traceback (most recent call last):
  File "main.py", line 297, in <module>
    Main()
  File "main.py", line 191, in Main
    pm.write_float(glow_manager + entity_glow * 0x38 + 0x4, float(r)) #R
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pymem\__init__.py", line 923, in write_float
    raise pymem.exception.MemoryWriteError(address, value, e.error_code)
pymem.exception.MemoryWriteError: Could not write memory at: 1068, length: 0.0 - GetLastError: 998

**Comment by JokinAce** [comment]
Delete the __pycache__ folder if it exists

**Comment by JokinAce** [comment]
Not responding.
